"""Collect density-ratio residual figures under one explicit naming scheme.

The source figures are preserved.  Canonical copies are written below
``reports/density_ratio_residual_figures`` and recorded in a CSV manifest.
"""
from __future__ import annotations

import csv
import re
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "reports" / "density_ratio_residual_figures"

EVENT_MAP = {
    "2018_NH": "2017-2018_NH_SSW",
    "2019_SH": "2019_SH_SSW",
    "2021_NH": "2020-2021_NH_SSW",
}


def canonical_name(event: str, platform: str, reference: str, index: str) -> str:
    return (
        f"{event}__{platform}__{reference}-density-ratio__{index}__"
        "linear-detrended__latitude-time.png"
    )


def add_copy(rows: list[dict[str, str]], source: Path, destination: Path, **metadata: str) -> None:
    if not source.exists():
        return
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, destination)
    rows.append(
        {
            **metadata,
            "source_file": str(source.relative_to(ROOT)),
            "canonical_file": str(destination.relative_to(ROOT)),
        }
    )


def collect_standardized_daily_ap(rows: list[dict[str, str]]) -> None:
    source_dir = ROOT / "reports" / "standardized_daily_Ap_linear_detrending"
    pattern = re.compile(
        r"SSW_(2018_NH|2019_SH|2021_NH)_SWARM_([ABC])_"
        r"density_ratio_msis_daily_Ap_linear_detrended\.png"
    )
    for source in sorted(source_dir.glob("*.png")):
        match = pattern.fullmatch(source.name)
        if not match:
            continue
        event = EVENT_MAP[match.group(1)]
        platform = f"SWARM-{match.group(2)}"
        destination = (
            OUT / "standardized_MSIS" / "event_window_daily_Ap" / event /
            canonical_name(event, platform, "standardized-MSIS", "daily-Ap")
        )
        add_copy(
            rows, source, destination, event=event, platform=platform,
            reference_model="standardized MSIS", geomagnetic_index="daily Ap",
            data_status="formal standardized product",
        )

    # The 2018/2019 NH event was generated by its dedicated standardized
    # three-index pipeline and therefore has a different historical source path.
    nh1819 = (
        ROOT / "reports" / "2018_2019_NH_SSW" /
        "three_index_linear_detrending" / "figures"
    )
    event = "2018-2019_NH_SSW"
    for satellite in "ABC":
        platform = f"SWARM-{satellite}"
        source = nh1819 / f"SSW_2018_2019_NH_SWARM_{satellite}_daily_Ap.png"
        destination = (
            OUT / "standardized_MSIS" / "event_window_daily_Ap" / event /
            canonical_name(event, platform, "standardized-MSIS", "daily-Ap")
        )
        add_copy(
            rows, source, destination, event=event, platform=platform,
            reference_model="standardized MSIS", geomagnetic_index="daily Ap",
            data_status="formal standardized product",
        )

    # GRACE-FO is available for the 2020/2021 NH event and uses the same
    # standardized daily-Ap linear-detrending figure design.
    event = "2020-2021_NH_SSW"
    platform = "GRACE-FO"
    source = (
        ROOT / "reports" / "2020_2021_NH_GRACE_FO_three_index_linear_detrending" /
        "figures" / "SSW_2021_NH_GRACE_FO_daily_Ap.png"
    )
    destination = (
        OUT / "standardized_MSIS" / "event_window_daily_Ap" / event /
        canonical_name(event, platform, "standardized-MSIS", "daily-Ap")
    )
    add_copy(
        rows, source, destination, event=event, platform=platform,
        reference_model="standardized MSIS", geomagnetic_index="daily Ap",
        data_status="formal standardized product",
    )


def collect_four_index_set(rows: list[dict[str, str]]) -> None:
    source_dir = ROOT / "reports" / "linear_detrending" / "figures"
    pattern = re.compile(
        r"(.+?)_(SWARM-[ABC]|GRACE-FO)_"
        r"(daily-Ap|ap-3hour|ap60-1hour|ap30-30min)_linear-detrending\.png"
    )
    index_dirs = {
        "daily-Ap": ("daily_Ap", "daily-Ap", "daily Ap"),
        "ap-3hour": ("ap_3hour", "ap-3hour", "3-hour ap"),
        "ap60-1hour": ("ap60_1hour", "ap60-1hour", "1-hour ap60"),
        "ap30-30min": ("ap30_30min", "ap30-30min", "30-minute ap30"),
    }
    for source in sorted(source_dir.glob("*.png")):
        match = pattern.fullmatch(source.name)
        if not match:
            continue
        event, platform, encoded_index = match.groups()
        index_dir, index_token, index_label = index_dirs[encoded_index]
        destination = (
            OUT / "standardized_MSIS" / "four_index_comparison" / index_dir / event /
            canonical_name(event, platform, "standardized-MSIS", index_token)
        )
        add_copy(
            rows, source, destination, event=event, platform=platform,
            reference_model="standardized MSIS", geomagnetic_index=index_label,
            data_status="four-index comparison product",
        )


def collect_legacy_daily_ap(rows: list[dict[str, str]]) -> None:
    source_dir = ROOT / "Figure" / "Ap_removal"
    sources = {
        "2D_detrend_only_temp_ap_2018.png": ("2017-2018_NH_SSW", "SWARM-A"),
        "2D_detrend_only_temp_ap_2018_SWARM-B.png": ("2017-2018_NH_SSW", "SWARM-B"),
        "2D_detrend_only_temp_ap_2018_SWARM-C.png": ("2017-2018_NH_SSW", "SWARM-C"),
        "2D_detrend_only_temp_ap_2019.png": ("2019_SH_SSW", "SWARM-A"),
        "2D_detrend_only_temp_ap_2019_SWARM-B.png": ("2019_SH_SSW", "SWARM-B"),
        "2D_detrend_only_temp_ap_2019_SWARM-C.png": ("2019_SH_SSW", "SWARM-C"),
        "2D_detrend_only_temp_ap_2021.png": ("2020-2021_NH_SSW", "SWARM-C"),
        "2D_detrend_only_temp_ap_2021_SWARM-A.png": ("2020-2021_NH_SSW", "SWARM-A"),
        "2D_detrend_only_temp_ap_2021_SWARM-B.png": ("2020-2021_NH_SSW", "SWARM-B"),
    }
    for filename, (event, platform) in sources.items():
        source = source_dir / filename
        destination = (
            OUT / "legacy_MSIS" / "daily_Ap" / event /
            canonical_name(event, platform, "legacy-MSIS", "daily-Ap")
        )
        add_copy(
            rows, source, destination, event=event, platform=platform,
            reference_model="legacy MSIS", geomagnetic_index="daily Ap",
            data_status="historical; do not use as formal standardized result",
        )


def main() -> None:
    rows: list[dict[str, str]] = []
    collect_standardized_daily_ap(rows)
    collect_four_index_set(rows)
    collect_legacy_daily_ap(rows)
    OUT.mkdir(parents=True, exist_ok=True)
    manifest = OUT / "figure_manifest.csv"
    fields = [
        "event", "platform", "reference_model", "geomagnetic_index",
        "data_status", "source_file", "canonical_file",
    ]
    with manifest.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)
    print(f"Collected {len(rows)} figures in {OUT}")


if __name__ == "__main__":
    main()
